### ISSUE TITLE
I can not open pkpass file on ios7

### ISSUE THREAD

**Issue by nvtruong** [eymengunay/php-passbook#30]
did it support ios 7 already?

**Comment by g-** [comment]
There is likely a problem with the pass.

Here is information from Apple about debugging passes.
> If the pass isn’t displayed and added to Wallet, check the log for a description of what went wrong. When testing in the iOS Simulator app, errors are logged to the system log, which you can view with the Console app. When testing on a device, errors are logged to the device’s console which you can view from the Xcode organizer window. Common errors include malformed JSON files, misspelled keys or values, pass type identifiers that don’t match your certificate, and signatures that omit the WWDR intermediate certificate.

https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html#//apple_ref/doc/uid/TP40012195-CH4-SW21

I've added a PassValidator to try and help prevent common problems that might prevent the pass from loading. If you let me know what the problem was that you encountered, I can add a check to this class.
