### ISSUE TITLE
Can't save pkpass on iOS 8

### ISSUE THREAD

**Issue by linkito** [eymengunay/php-passbook#32]
Hi.

I trying to run the passbook sample demo, and I don't have problems to generate the .pkpass file... but I can't open it in iOS 8.3...

A question... Have I to export the Private Key of iPhone Development Cert, or the iPhone Distribution Cert?

And the TEAM, is the TEAM of Distribution, or the Development?

Now, I'm using the .P12 of the Private Key of the iPhone Distribution Cert, and the same for the TEAM ID (Distribution Cert).

Anybody can help me?

Thanks!

**Comment by altpoint** [comment]
We have a similar problem =(

**Comment by subharb** [comment]
I'm having the same issue, the .pkpass is created sucessfully and can be viewed with the Pass Viewer, but when I drag&drop to the iOS 8.4 Simulator, safari says "Download failed, Safari cannot download this file".
I've been trying to debug it but I can't find the mistake.

Any ideas?

**Comment by welsby** [comment]
Same here, the sample.pkpass but my event will open on OSX, but not in iOS. I know they've got a lot stricter from iOS6 onwards but not sure where to debug it, already exported/converted my certificates twice so pretty confident all the settings and certs are correct.

**Comment by g-** [comment]
This happens when there is a problem with the pass. The preview will show the pass successfully, but it will not be added to Wallet (Passbook).

Here is information from Apple about debugging passes.

> If the pass isn’t displayed and added to Wallet, check the log for a description of what went wrong. When testing in the iOS Simulator app, errors are logged to the system log, which you can view with the Console app. When testing on a device, errors are logged to the device’s console which you can view from the Xcode organizer window. Common errors include malformed JSON files, misspelled keys or values, pass type identifiers that don’t match your certificate, and signatures that omit the WWDR intermediate certificate.

https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html#//apple_ref/doc/uid/TP40012195-CH4-SW21

I've added a PassValidator to try and help prevent common problems that might prevent the pass from loading (e.g. missing an icon or serial number is a number instead of a string). If you let me know what the problem was that you encountered, I can add a check to this class.
