### ISSUE TITLE
This pass is no longer valid

### ISSUE THREAD

**Issue by dator** [eymengunay/php-passbook#43]
Hi,

I'm trying to use your library but i have an issue.

Here is my code:

https://gist.github.com/dator/ff9e8a7bc3acc595fe25

And with this code, i always get "This pass is no longer valid".
My P12 looks fine, the passbook is created but not valid and Qrcode is not displaying.

<img width="157" alt="capture d ecran 2015-12-03 a 15 47 02" src="https://cloud.githubusercontent.com/assets/46281/11563683/7f3147b6-99d5-11e5-9273-c54fbdeba9c0.png">

Do you have an idea ?

Thanks a lot,

**Comment by g-** [comment]
Hello,

Assuming that in your real code the latitude and longitude are set and the environment variables are passed into the PassFactory rather than strings, the problem is likely with the associatedStoreIdentifiers. This must be an array of integers, so it is likely that the string value is causing the pass to be invalid.

Have a look at this…

	http://stackoverflow.com/questions/14208466/list-app-on-back-of-pass-in-testing-and-adhoc-distrbution-mode

Hope that helps.

-g

**Comment by panagath** [comment]
I have the same issue. Adding "associatedStoreIdentifiers" doesn't seem to work. Any other suggestions?

**Comment by g-** [comment]
Can you provide more details about the problem and the code that you are using?

**Comment by panagath** [comment]
Well I found the answer.The Apple's WWDR intermediate cerficate has expired. Hope this answer helps someone. More info here:

https://developer.apple.com/support/certificates/expiration/
