### ISSUE TITLE
Packagist does not list release 2.2.0

### ISSUE THREAD

**Issue by lstrojny** [eymengunay/php-passbook#87]
2.2.0 is listed on https://github.com/eymengunay/php-passbook/tags but it’s not listed at https://packagist.org/packages/eo/passbook. Packagist also says "This package is not auto-updated.". I hit the "upgrade now" button but that didn't catch it either.

### Edit
Looks like the `composer.json` in 2.2.0 contains `version: 3.0.0`. That doesn’t seem right

**Comment by lstrojny** [comment]
Bump

**Comment by eymengunay** [comment]
Dear @lstrojny ,

Thank you for your patience! Unfortunately I'm not actively maintaining this project as I used to so I'm now basically merging PR's from contributors.

I have looked into this issue and as you have suggested there was a problem with the version 2.2.0. Additionally I had wrongly tagged that PR as 2.2.0 however it should have been a major version update due to many breaking changes introduced by 6df4877d249ff51786dd0ad439c5f3ae9ec2deb1.

Latest version that supports PHP 5.x is now 2.1.0, and there is also v3 which requires >= 7.4

I have also updated packagist so you should be able too see these changes also there. I hope this resolves your issue.

**Comment by lstrojny** [comment]
Thank you very much and happy holidays!

**Comment by eymengunay** [comment]
Thank you for your understanding. I wish you happy holidays as well.

PS: I’m closing this issue however if there is something else feel free to open a new issue or simply add it here.
